---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(latex2exp)
library(readr)
library(patchwork)
```

```{r}
vae <- read_csv("test_data/vae_test.txt", col_types = cols(
  beta = col_double(),
  L = col_factor(),
  re = col_double(),
  kl = col_double(),
  `mll (crude)` = col_double(),
  `mll (importance)` = col_double()
))
vae 
```
```{r}
vae %>%
  rename(crude=`mll (crude)`, importance=`mll (importance)`) %>%
  pivot_longer(cols = `crude`:`importance`, names_to = "type", values_to = "mll") %>%
  ggplot() +
  geom_line(aes(x=beta, y=mll), size=0.5, color="navy") +
  geom_label(data=~.x %>% filter(L == 50 & type == 'crude'), aes(x=0.2, y=-750, label="ELBO"), color="tomato", hjust=0) +
  geom_label(data=~.x %>% filter(L == 50 & type == 'crude'), aes(x=0.2, y=-850, label="MLL (estimate)"), color="navy", hjust=0) +
  geom_point((aes(x=beta, y=mll)), size=0.7, color="navy") +
  geom_line(aes(x=beta, y=-re -kl), color="tomato", size=0.7) +
  geom_point(aes(x=beta, y=-re -kl), color="tomato", size=0.9) +
  xlab(TeX("$\\beta$")) +
  ylab("Logarithmic likelihood") +
  facet_grid(type~L, scales="free") +
  ggtitle(TeX("$\\beta$-VAE ELBO and marginal log-likelihood estimation"), subtitle = TeX("Log-likelihood values for $L \\in \\{50, 100\\}$ with crude Monte Carlo estimation and importance sampling")) +
  theme_light() +
  theme(plot.subtitle = element_text(color="gray50"))
```

```{r}
ggsave('./plots/vae.png', device='png', width = 8, height = 5)
```

```{r}
ncp <- read_csv("test_data/ncp_test.txt", col_types = cols(
  beta = col_double(),
  L = col_factor(),
  re = col_double(),
  kl = col_double(),
  `mll (crude)` = col_double(),
  `mll (importance)` = col_double()
))
ncp
```

```{r}
ncp %>%
  rename(crude=`mll (crude)`, importance=`mll (importance)`) %>%
  pivot_longer(cols = `crude`:`importance`, names_to = "type", values_to = "mll") %>%
  ggplot() +
  geom_line(aes(x=beta, y=mll), size=0.5, color="navy") +
  geom_label(data=~.x %>% filter(L == 50 & type == 'crude'), aes(x=0.2, y=-750, label="ELBO"), color="tomato", hjust=0) +
  geom_label(data=~.x %>% filter(L == 50 & type == 'crude'), aes(x=0.2, y=-850, label="MLL (estimate)"), color="navy", hjust=0) +
  geom_point((aes(x=beta, y=mll)), size=0.7, color="navy") +
  geom_line(aes(x=beta, y=-re -kl), color="tomato", size=0.7) +
  geom_point(aes(x=beta, y=-re -kl), color="tomato", size=0.9) +
  xlab(TeX("$\\beta$")) +
  ylab("Logarithmic likelihood") +
  facet_grid(type~L, scales="free") +
  ggtitle(TeX("NCP-VAE ELBO and marginal log-likelihood estimation"), subtitle = TeX("Log-likelihood values for $L \\in \\{50, 100\\}$ with crude Monte Carlo estimation and importance sampling")) +
  theme_light() +
  theme(plot.subtitle = element_text(color="gray50"))
```

```{r}
ggsave('./plots/ncp.png', device='png', width = 8, height = 5)
```

```{r}
discr <- read_csv("test_data/discriminator_test.txt", col_types = cols(
  beta = col_factor(),
  L = col_factor(),
  bce = col_double()
))
discr
```
```{r}
low <- discr %>%
  filter(L == 50) %>%
  ggplot() +
  scale_x_reverse(labels=scales::label_number_si()) +
  ylab(NULL) + 
  xlab("BCE") +
  scale_fill_brewer(type="div", palette = 5, direction = 1) +
  ggtitle("Discriminator binary cross entropy (BCE)", subtitle = "Latent space dimension: 50") +
  geom_col(aes(y=beta, x=bce, fill=L), show.legend = F) +
  geom_text(aes(bce, beta, label=round(bce,2), color=bce > .1, hjust=bce < .1), size=5, show.legend = F) +
  scale_color_manual(values = c("black", "white")) +
  scale_discrete_manual("hjust", values = c(-0.2, 1.2)) +
  theme_minimal() +
  theme(panel.grid.major.y = element_blank(), axis.text.y = element_blank()) +
  theme(plot.subtitle = element_text(color="gray50"))


high <- discr %>%
  filter(L == 100) %>%
  ggplot() +
  geom_col(aes(y=beta, x=bce, fill=L), show.legend = F) +
  geom_text(aes(bce, beta, label=round(bce,2), color=bce < .1, hjust=bce > .1), size=5, show.legend = F) +
  scale_color_manual(values = c("white", "black")) +
  scale_discrete_manual("hjust", values = c(-0.2, 1.2)) +
  theme_minimal() +
  scale_fill_brewer(type="div", palette = 3, direction = -2) +
  ggtitle("", subtitle = "Latent space dimension: 100") +
  xlim(c(0,0.3)) +
  ylab(TeX("\\beta")) +
  xlab("BCE") +
  theme(panel.grid.major.y = element_blank(),
            axis.text.y = element_text(hjust=0.5),
            axis.title.y = element_text(angle=0,margin = margin(r=-10))) +
  theme(plot.subtitle = element_text(color="gray50"))

low + high
```
```{r}
ggsave('./plots/discr.png', device='png', width = 8, height = 4)
```

